### ISSUE TITLE
menvcfg.HADE=0 irrevocably disables Svadu?

### ISSUE THREAD

**Issue by pdonahue-ventana** [riscv/riscv-svadu#2]
> When menvcfg.HADE is zero, the implementation behaves as though Svadu is not implemented. If Svadu is not implemented, menvcfg.HADE is read-only zero.

Because these sentences are back-to-back, this reads like A=>B and B=>C which means that A=>C.  When HADE is zero then HADE is read-only zero.  That would mean that once it's zero then it cannot be changed.  That would, for instance, preclude M mode from world-switching hypervisors with different Svadu support (or M mode emulation of the H extension and switching between different guest OSes with different Svadu support, something that henvcfg.HADE does allow).  I suspect that this wasn't the intention.

**Comment by ved-rivos** [comment]
Indeed that is not the intention. Perhaps changing from "behaves as though Svadu is not implemented" to "behaves as though Svadu were not implemented" may address the confusion?

**Comment by pdonahue-ventana** [comment]
I'm not sure but there are probably precedents in other extensions.  This just stood out to me because those sentences are right next to each other.

**Comment by ved-rivos** [comment]
The language follows language for other bits in the same register. For example 

> When PBMTE=0, the implementation behaves as though Svpbmt were not implemented for VS-stage address translation. If Svpbmt is not implemented, PBMTE is read-only zero.

**Comment by pdonahue-ventana** [comment]
OK.  That somehow does seem clearer to me, but maybe I'm just overanalyzing the whole thing.  I'd be fine with changing "is not" to "were not" like PBMTE.

**Comment by ved-rivos** [comment]
Updated  as such.
