### ISSUE TITLE
ADUE should be under S-mode control

### ISSUE THREAD

**Issue by jrtc27** [riscv/riscv-svadu#21]
Currently ADUE lives in menvcfg, which means M-mode needs to decide what to set it to. M-mode itself does not care, because it is not subject to translation. What does care is S-mode, as it's the one that has to deal with the traps or the PTEs automatically being updated underneath it. Therefore it only makes sense for ADUE to be under S-mode's control, like how satp.MODE is under its control. If it's under M-mode control then you're left with two options:
1. Require an SBI call to set it
2. Have M-mode hard-code which to use

1 is completely gratuitous and would be yet another instance of adding an SBI call to paper over a bad ISA design (like HPM configuration; until recently, a lack of Sstimecmp; and, in the more distant past, how the translation mode used to be configured by M-mode, not in satp.MODE). 2 effectively renders ADUE useless as you might as well just hardwire the bit to whatever your firmware sets it to; if it's set to 0 then Svadu effectively doesn't exist in your hardware and you're back to trapping and emulating, but if it's set to 1 then your OS needs to be prepared to handle the updates, which an RVA20 or RVA22 OS may not be, given Svade is mandatory in RVA20 and RVA22, and so you'd break compatibility of your new hardware with an older OS that might otherwise work if your hardware otherwise is RVA20/22-conforming.

Technically there's 3. Make your firmware user-configurable, but requiring the user to configure things like that gives an awful experience, and will result in countless cases of people either breaking their systems by enabling it or making their systems slower than needed by disabling it. One only needs to look at the history of PC BIOS configuration to understand that anything other than "inserting OS media and booting just works" is a bad corner to box yourself into.

**Comment by jrtc27** [comment]
For reference, the equivalent ISA extension on the AArch64 side, FEAT_HAFDBS, puts its equivalent configuration in TCR_EL1, an EL1 (S-mode) controlled system register. This perfectly fits the model of how S-mode OSes work and want to configure translation.

**Comment by ved-rivos** [comment]
The Privileged architecture defines `menvcfg` to hold controls for the execution environment it governs. 

The `menvcfg` has control bits for: `STCE` - to enable the use of `stimecmp` by S-mode, `PBMTE` - to enable the use of page-based memory types for S-mode page tables, `CB*` - various controls to enable the use of Zicbom, Zicboz, and Zicbop instructions. The `menvcfg` will hold controls for future extensions like [Smnpm](https://github.com/riscv/riscv-j-extension/blob/master/zjpm/instructions.adoc?plain=1#L28), [Zicfiss](https://github.com/riscv/riscv-cfi/blob/main/cfi_backward.adoc?plain=1#L78), and [Zicfilp](https://github.com/riscv/riscv-cfi/blob/main/cfi_forward.adoc?plain=1#L130). The Svadu extension in this regards does not diverge from the Privileged architecture.

As you noted requires an SBI call to enable the feature is required and is being [discussed](https://lists.riscv.org/g/tech-prs/message/620) in PRS TG. An OS not aware of the feature will not request activation of the feature. As these are environment configurations and are not expected to be dynamic. In some cases - for example, for security features - there may be a way to prohibit a later disabling of the control and this becomes possible through SBI enforced policy.

**Comment by jrtc27** [comment]
Using an SBI call is gratuitous. It should be under S-mode's direct control. This is absurd.

**Comment by jrtc27** [comment]
And note that there is a big difference between STCE, PBMTE and CB* vs ADEU. For the former, it's M-mode saying S-mode _may_ use the feature, but it can opt not to. For the latter, it's M-mode saying S-mode _is_ using the feature. Both have value in different cases. For STCE you need M-mode (or, really, HS-mode) to opt into (V)S-mode using it so that it knows to context switch as needed. For ADEU you do not. For PBMTE I don't really understand the point of the bit, but hey. For CB* they're there so you can (a) trap-and-emulate if needed for some reason (b) turn invalidate into flush for your own security reasons. Whereas for ADEU it's about whether the OS itself wants that feature and its consequences or not.

**Comment by jrtc27** [comment]
> As these are environment configurations and are not expected to be dynamic.

So what happens when I kexec a different kernel?

**Comment by ved-rivos** [comment]
The `menvcfg` does allow the machine mode to create a virtual machine for the S mode. You provided some good examples - including - the ability to trap and emulate A/D bit updates if desired. I may have used a poor choice of words by saying "not expected to be dynamic". I should have rather stated that it is expected to be mostly static as in not changed frequently. A kexec or invocation of a UEFI runtime service (e.g., after invoking `SetVirtualAddressMap`) may require switching to a different execution environment. An operating system doing `kexec` to a new OS that does not understand the new capabilities would need to turn off these capabilities prior to switching. The new OS may then reactivate as needed.

**Comment by ved-rivos** [comment]
Having `ADUE` in `menvcfg` aligns with the privileged architecture's guidelines for such environment configurations. It also allows M-mode to virtualize the machine for S-mode, if desired. The use of an SBI call at OS startup to activate the feature should not be a major issue as it is for an OS to change this setting.

**Comment by jrtc27** [comment]
That is, having it *a* bit in an M-mode-controlled register is fine, but it is not sufficient. There needs to be an S-mode-controlled bit. Otherwise you break the ability to have a platform that is simultaneously compatible with RVA22 and RVA23.

**Comment by jrtc27** [comment]
That is:

menvcfg.ADUE can exist to allow S-mode to make use of Svadu. But some sfoo.ADUE should also exist to allow S-mode to opt into using it when supported, but remains as 0 for backwards compatibility. This is the industry-standard way to make extensions like this backwards-compatible.

**Comment by ved-rivos** [comment]
Even if the capability unconditionally should not break an RVA22 OS. The default RISC-V qemu model always did H/W updating of A/D bits and has not been an issue. Please share if there is an instance of a RVA22 OS that would not function if this capability were turned on. Adding another S-mode control is not highly justified and locating this bit in `menvcfg` should not lead to a incompatibility with RVA22 OS.

**Comment by jrtc27** [comment]
> The default RISC-V qemu model always did H/W updating of A/D bits and has not been an issue

Indeed, and I hate that RVA20/RVA22 outlaw that behaviour.

> Please share if there is an instance of a RVA22 OS that would not function if this capability were turned on.

That doesn't matter. The RVA22 spec is what it is, so a system cannot claim to be compatible with RVA22 and RVA23 OSes simultaneously, regardless of whether or not the RVA22 OSes that people run on top of them in practice support additional things that RVA22 explicitly forbids hardware from doing.

**Comment by jrtc27** [comment]
Note also that Svadu is _not_ just reimplementing the behaviour that QEMU implements and was previously allowed. Its atomicity and speculation rules are weaker; in particular, A is allowed to be updated speculatively by Svadu, but not by the old scheme documented in the privileged spec.

**Comment by ved-rivos** [comment]
I am not suggesting that but wanted to understand if there is a real breakage that was known. About S-mode control bit, the value of adding new S and VS CSRs is low considering this setting needs to be changed infrequently. The current placement follows the privileged architecture on placement of such controls.

**Comment by jrtc27** [comment]
> I am not suggesting that but wanted to understand if there is a real breakage that was known. About S-mode control bit, the value of adding new S and VS CSRs is low considering this setting needs to be changed infrequently. The current placement follows the privileged architecture on placement of such controls.

Please give me an example of a ratified spec that requires an SBI call to enable it from S-mode but conceptually doesn't need to, and is not in the list of specs already mentioned that are getting ISA extensions to avoid that.

**Comment by ved-rivos** [comment]
> so a system cannot claim to be compatible with RVA22 and RVA23 OSes simultaneously
A system that is RVA23 OS compatible implies it is also RVA22/RVA20 OS compatible - so not sure what is implied by a system being not compatible with RVA22 and RVA23 OS simultaneously. 

While it is possible define the control as a pair of control bits - one that is M and HS privileged and another that is S and VS privileged - it is not the way all other control bits have been defined in the Priv. architecture. There does not seem to be a significant value in requiring additional hardware/architecture for doing this uniquely for `ADUE` given that this control is expected to be fairly static.

**Comment by jrtc27** [comment]
> A system that is RVA23 OS compatible implies it is also RVA22/RVA20 OS compatible

RVA20/22 mandate trapping for A/D. RVA23 allows Svadu. Therefore to be RVA20/22/23 compatible you cannot enable ADUE in firmware, the OS has to opt in. The only sane way to do that is via an S-mode-controlled CSR bit somewhere like other production architectures do for these things. Doing an SBI call for it is not sane, it is a bogus workaround for poor ISA design. Please learn from other ISAs and do not deviate in ways that make RISC-V a mess. SBI calls should be solely for things that a higher-privileged entity *must* be involved in, either due to it inherently being a privileged operation or due to the higher-privileged entity needing to be aware of it for other reasons (e.g. whether it should emulate misaligned accesses). Svadu has no such requirement, therefore an SBI call to enable it is wholly inappropriate.

**Comment by ved-rivos** [comment]
While a second control toggleable at the S/VS level could be a legitimate architectural option, we believe the current approach of using the SBI offers similar functionality. Given the infrequent need to modify this setting, the overhead introduced by an SBI call is not a significant concern. Therefore, we don't see a compelling reason to make a change at this point.

**Comment by jrtc27** [comment]
Does it work? Yes

Does performance matter? No

Is it sensible? No

That's it in a nutshell. Putting stuff in firmware that has no reason to be in firmware is bad design. It bloats firmware (which may be space-constrained), adds to its attack surface and overcomplicates everything compared with a single CSR write in S-mode.

See https://lists.riscv.org/g/tech-prs/topic/moving_sbi_functions_out_of/101518223 for various comments from important parties in the RISC-V ecosystem about precisely this problem of not putting things in M-mode that don't need to be.

**Comment by jrtc27** [comment]
Taking it to an extreme:

* stvec could require an SBI call to set given an OS just sets it once at boot
* satp.MODE could have been left as requiring an SBI call by living in mstatus like it used to be, given an OS doesn't typically change it during context switch, only the base address and ASID
* various fields in senvcfg could be left under M-mode control and require SBI calls because an OS likely chooses its policy once at boot (possibly changing in response to a sysctl or similar)

There is a tried and tested approach used by industry for introducing backwards-incompatible extensions, which this is from the perspective of RISC-V Profiles. That approach is to have two separate bits (omitting one or the other when there is no compatibility concern for that party):

1. Under the control of M-mode, a bit saying "I am happy for S-mode to use this"
2. Under the control of S-mode, a bit saying "I want to enable this" (gated on the M-mode-controlled bit)

I am peeved that this is being eschewed and the "solution" proposed to bodge things by papering over it in firmware where it has no place and adds completely unnecessary bloat there (and, I might add, more code and complexity for the OS, because making an ECALL is more code and has more requirements than just frobbing a CSR). If you talk to any prominent OS developer, or, for example, Arm's chief architects and engineers, they will tell you that the approach outlined above is exactly how things should be done. That you have gone to freeze without it is on you and is no excuse for doing things in a badly-designed manner; the whole point of RFCs and public reviews is so people can tell you when your design is bad.

(and of course s/S/VS/;s/M/HS/ for the hypervisor case)

**Comment by ved-rivos** [comment]
Summarizing:

The placement of these ADUE controls follows the Priv. arch. placement of similar controls in `menvcfg`/`henvcfg` such as `PBMTE`, `CBZE`, or `CBCFE` or controls in upcoming extensions such as pointer masking and counter delegation. In all these cases an OS/hypervisor, if it needs to change one of these bits from the default that it was given at boot time, would make an environment call from HS/VS mode up to M/HS mode, via an SBI, to request a change to the bit's setting.  This generally would be part of the OS/hypervisor's boot process.

With the suggestion to add a second set of S/VS mode controls of controls, the existing set of controls would allow M/HS mode to choose whether to allow S/VS mode to use the added controls to directly enable Svadu or not.

Besides allowing delegation, the `*envcfg` controls allow M/HS modes to present a virtual machine to S/VS modes. Supporting usages such as page-table shadowing may require M/HS to use page-fault exceptions to shadow A/D bits into the virtual page tables.

While such a control at the S/VS level could be a legitimate architectural option, the current approach of using the SBI offers similar functionality. And, in particular, given the rare need to modify this setting (e.g. one time when booting an OS/hypervisor), the overhead introduced by an SBI call is insignificant and does not present a compelling reason to introduce additional
hardware arch functionality. And this strategy is consistent with other execution environment config bits (as noted above).

**Comment by jrtc27** [comment]
For the record: I fundamentally disagree with the approach being adopted here. You can paper over it with firmware interfaces all you like, but it's fundamentally putting the control in the wrong place in the ISA, does not make sense, and is at odds with how other sensible ISAs have done this kind of thing for decades.
