### ISSUE TITLE
allow speculative G-stage D bit updates for VS-stage A bit updates

### ISSUE THREAD

**Issue by ingallsj** [riscv/riscv-svadu#4]
If we're opening the ISA text up for revision, we should add this relaxation: proposed text in **bold** at the end

> - When two-stage address translation is in use, an explicit access may cause both VS-stage and G-stage PTEs to be updated. The following rules apply to all PTE updates caused by an explicit or an implicit memory accesses.
> The PTE update must be atomic with respect to other accesses to the PTE, and must atomically check that the PTE is valid and grants sufficient permissions. Updates of the A bit may be performed as a result of speculation, but updates to the D bit must be exact (i.e., not speculative), and observed in program order by the local hart. **Updates of the D bit may be performed in G-level page tables as a result of speculative updates of the A bit in VS-level page tables.**

**Comment by ved-rivos** [comment]
As the memory as referenced by the G-stage PTEs is modified this makes sense.

**Comment by ved-rivos** [comment]
PR #8 to address this issue.
