### ISSUE TITLE
"Svadu extension requires the page tables to be located in cacheable main memory PMA regions"

### ISSUE THREAD

**Issue by ingallsj** [riscv/riscv-svadu#5]
Is this a requirement on
- hardware to check that page table walks are always to cacheable main memory, otherwise fault, or
- software to place their page tables in cacheable main memory?

I'm hoping for the latter, so I don't need to add `requires_cacheable` hardware to the PMA checks for page table walks.

May I suggest this language instead?

"Svadu extension architecturally guarantees that cacheable main memory PMA regions support hardware updating of PTE A/D bits."

**Comment by ved-rivos** [comment]
The requirement is the former i.e. the extension requires the page tables to be in cacheable main memory PMA regions. This may not be a new check to the page table walks as the page table walks check the supported access type PMAs provides indications on whether hardware page-table reads and hardware page-table writes are supported by a memory region. The AR suggested this restriction as presently the architecture lacks a compare-and-swap instruction and for A/D bit management software has to use a LR/SC sequence and those are supported on cacheable main memory.

**Comment by ingallsj** [comment]
> The requirement is the former i.e. the extension requires the page tables to be in cacheable main memory PMA regions.

If that is your intent, I recommend making that new fault check explicit:

"Svadu extension requires the page tables to be located in cacheable main memory PMA regions, otherwise raise an access-fault exception [corresponding to the original access type]."

**Comment by ingallsj** [comment]
> This may not be a new check to the page table walks as the page table walks check the supported access type PMAs provides indications on whether hardware page-table reads and hardware page-table writes are supported by a memory region.

Using an open-source example of an existing system, the PMAs in Rocket-chip currently do _not_ separately distinguish reads and writes for page table walks vs loads and stores.  So, this would be a new check.  E.g. in https://github.com/chipsalliance/rocket-chip/blob/master/src/main/scala/rocket/TLB.scala, something like `cmd_ptw` in several places similarly to `cmd_lrsc`.

**Comment by ingallsj** [comment]
> The AR suggested this restriction as presently the architecture lacks a compare-and-swap instruction and for A/D bit management software has to use a LR/SC sequence and those are supported on cacheable main memory.

LR/SC already has a cacheable memory type PMA check, which this new PTW cacheable hardware check is redundant with.  Can we please not add any new exception checks in this extension?

I'll again request this language instead:

"Svadu extension architecturally guarantees that cacheable main memory PMA regions support hardware updating of PTE A/D bits."

Or, to use the language from https://github.com/riscv/riscv-profiles/blob/main/profiles.adoc#6-rva22-profiles

"**Svadu** Main memory regions with both the cacheability and coherence PMAs must support hardware updating of PTE A/D bits."

**Comment by ved-rivos** [comment]
For an implementation that does not support Svadu, page table walks  are only loads - the page table walker would not do a store. However when Svadu is active, the page table walk needs to do a AMO to update the A/D bits. So such a page table walker would be required - in addition to checking the PMA for load access - also check the atomicity  PMA. Would that not be the case?
The fault is already detected in the  process - step 2 and step 7a - cause an access fault of the original kind if a PMA or PMP rule violation occurs.

**Comment by ingallsj** [comment]
Continuing with the open-source Rocket-chip example: systems can also support un-cached atomics.

**Comment by ved-rivos** [comment]
I did not realize that Rocket chip support hardware updating of A/D bits in uncached memory.

**Comment by ingallsj** [comment]
To be precise, Rocket-chip already supports atomics in uncached memory, and not currently hardware updating of A/D bits.

**Comment by ved-rivos** [comment]
Have requested AR opinion about relaxing this requirement.

**Comment by ved-rivos** [comment]
Propose to update this statement as follows:
"Svadu requires page tables to be located in memory with hardware page-table write access and RsrvEventual PMA."

This is a reflection of the need for software to also be able to do atomic accesses to A&D bits that hardware does atomic updates to. Which today can only be done using LR/SC (to perform a CAS operation) - which can only be done in memory with RsrvEventual PMA.

**Comment by ingallsj** [comment]
That's fine as a software requirement, but it is unnecessary to add additional special RsrvEventual fault checking hardware on the page table walks themselves.

**Comment by ved-rivos** [comment]
The AR conclusion is that the architecture will require a MMU that supports Svadu, as part of its PMA checks, implement these checks to be compliant to the architecture.

**Comment by ved-rivos** [comment]
Merged PR#12. Marking as resolved.

**Comment by ingallsj** [comment]
Yes, I perfectly understand the typical use case.

I'm still not understanding why RISC-V _needs_ this additional check on page table walks to flag bad Operating System setup at the time of the page table walk.  Whenever the OS tries to do a LR/SC to a non-cacheable page table entry, then it will get faulted.  Other contemporary ISAs do just fine without this check, and I don't know that it's really needed.

> typical PMA implementations

I gave an example of open-source Rocket-chip that distinguishes between supporting RsrvEventual and Atomics, and Rocket-chip is the basis for several other open-source cores too, so I'd say that's evidence that some typical PMA implementations do distinguish these Atomics to non-cacheable memory versus LR/SC only in cacheable memory.

**Comment by ingallsj** [comment]
About LR/SC: why can't the operating system use AMOSWAP to swap in a zero PTE while it decides what to do with the old PTE?

**Comment by ved-rivos** [comment]
So if the PTE is zeroed then it makes the PTE invalid. This may cause a page fault unless the application using  that virtual address is de-scheduled and that would not be desirable
