### ISSUE TITLE
re-statement of translation process

### ISSUE THREAD

**Issue by ingallsj** [riscv/riscv-svadu#6]
The extension proposal says

> "**except** that step 7 of the translation process is as follows: ..."

and then re-states the **existing** step 7 of the translation process.  This is unnecessary, confusing, and misleading in the scope of what this ISA extension is trying to change.

**Comment by ingallsj** [comment]
Did you instead mean to say that the Svadu extension is **required** to perform the hardware updates in step 7 of the translation process?  If so, then I recommend this text instead in the extension: proposed text in **bold** at the end

> The translation of virtual addresses (or guest physical addresses) to physical (or guest physical) addresses is accomplished with the same algorithm as specified in the Supervisor-Level ISA extension (section 4.3.2) and as modified by the hypervisor extension (section 8.5.1), except that step 7 of the translation process is as follows:
> 7. If pte.a = 0, or if the original memory access is a store and pte.d = 0, either raise a page-fault exception corresponding to the original access type, or **if the Svadu extension is implemented**:
> ...

**Comment by ved-rivos** [comment]
That makes sense. I will also seek a clarification on AR on how the text be updated to be coexisting Ssptead extension.

**Comment by ved-rivos** [comment]
PR #9 to address this issue.
